<?php

//----------------------------------------------
//----------Motivation Slider Post Type 
//----------------------------------------------
$labels = array(
    'name' => _x('happyclient', 'Post Type General Name', 'oc'),
    'singular_name' => _x('Happy Client', 'Post Type Singular Name', 'oc'),
    'menu_name' => __('Happy Client', 'oc'),
    'name_admin_bar' => __('Post Type', 'oc'),
    'archives' => __('Item Archives', 'oc'),
    'parent_item_colon' => __('Parent Item:', 'oc'),
    'all_items' => __('All Items', 'oc'),
    'add_new_item' => __('Add New Item', 'oc'),
    'add_new' => __('Add New', 'oc'),
    'new_item' => __('New Item', 'oc'),
    'edit_item' => __('Edit Item', 'oc'),
    'update_item' => __('Update Item', 'oc'),
    'view_item' => __('View Item', 'oc'),
    'search_items' => __('Search Item', 'oc'),
    'not_found' => __('Not found', 'oc'),
    'not_found_in_trash' => __('Not found in Trash', 'oc'),
    'featured_image' => __('Featured Image', 'oc'),
    'set_featured_image' => __('Set featured image', 'oc'),
    'remove_featured_image' => __('Remove featured image', 'oc'),
    'use_featured_image' => __('Use as featured image', 'oc'),
    'insert_into_item' => __('Insert into item', 'oc'),
    'uploaded_to_this_item' => __('Uploaded to this item', 'oc'),
    'items_list' => __('Items list', 'oc'),
    'items_list_navigation' => __('Items list navigation', 'oc'),
    'filter_items_list' => __('Filter items list', 'oc'),
);
$args = array(
    'label' => __('Happy Client', 'oc'),
    'description' => __('Post Type Description', 'oc'),
    'labels' => $labels,
    'supports' => array('title', 'editor', 'excerpt',),
    'taxonomies' => array('category', 'post_tag'),
    'hierarchical' => false,
    'public' => true,
    'show_ui' => true,
    'show_in_menu' => true,
    'menu_position' => 5,
    'show_in_admin_bar' => true,
    'show_in_nav_menus' => true,
    'can_export' => true,
    'has_archive' => true,
    'exclude_from_search' => false,
    'publicly_queryable' => true,
    'capability_type' => 'page',
);
register_post_type('Happy Client', $args);

$labels = array(
    'name' => _x('faculty', 'Post Type General Name', 'oc'),
    'singular_name' => _x('faculty', 'Post Type Singular Name', 'oc'),
    'menu_name' => __('Faculty', 'oc'),
    'name_admin_bar' => __('Post Type', 'oc'),
    'archives' => __('Item Archives', 'oc'),
    'parent_item_colon' => __('Parent Item:', 'oc'),
    'all_items' => __('All Items', 'oc'),
    'add_new_item' => __('Add New Item', 'oc'),
    'add_new' => __('Add New', 'oc'),
    'new_item' => __('New Item', 'oc'),
    'edit_item' => __('Edit Item', 'oc'),
    'update_item' => __('Update Item', 'oc'),
    'view_item' => __('View Item', 'oc'),
    'search_items' => __('Search Item', 'oc'),
    'not_found' => __('Not found', 'oc'),
    'not_found_in_trash' => __('Not found in Trash', 'oc'),
    'featured_image' => __('Featured Image', 'oc'),
    'set_featured_image' => __('Set featured image', 'oc'),
    'remove_featured_image' => __('Remove featured image', 'oc'),
    'use_featured_image' => __('Use as featured image', 'oc'),
    'insert_into_item' => __('Insert into item', 'oc'),
    'uploaded_to_this_item' => __('Uploaded to this item', 'oc'),
    'items_list' => __('Items list', 'oc'),
    'items_list_navigation' => __('Items list navigation', 'oc'),
    'filter_items_list' => __('Filter items list', 'oc'),
);
